Repository informalsystems/hermes, pull requests merged in 2021-08, with the labels that each got.

#1266 Update compatibility.rs
  relayer/src/chain/cosmos/compatibility.rs
Labels: needs guide update

#1250 Implement checks to identify dependencies that do not support `no_std`
  no-std-check/Cargo.lock
  no-std-check/Cargo.toml
  no-std-check/Makefile
  no-std-check/README.md
  no-std-check/src/lib.rs
Labels: no-std

#1176 Adding gaiad v5.0.5 support on CI
  .changelog/unreleased/features/1175-update-ci.md
  ci/README.md
  ci/build-ibc-chains.sh
  ci/chains/gaia/v5.0.5/ibc-0/config/addrbook.json
  ci/chains/gaia/v5.0.5/ibc-0/config/app.toml
  ci/chains/gaia/v5.0.5/ibc-0/config/client.toml
  ci/chains/gaia/v5.0.5/ibc-0/config/config.toml
  ci/chains/gaia/v5.0.5/ibc-0/config/genesis.json
  ci/chains/gaia/v5.0.5/ibc-0/config/gentx/gentx-0a67e76f6743997bde26b522ef43e886b1baa95d.json
  ci/chains/gaia/v5.0.5/ibc-0/config/node_key.json
  ci/chains/gaia/v5.0.5/ibc-0/config/priv_validator_key.json
  ci/chains/gaia/v5.0.5/ibc-0/keyring-test/3dccd2a276b243a6f235f16430bb45828989382d.address
  ci/chains/gaia/v5.0.5/ibc-0/keyring-test/4da888907bd0f30dab598252aea96a3ae97b97ee.address
  ci/chains/gaia/v5.0.5/ibc-0/keyring-test/d96ea1dad97dd40751c1d8fcd577d3eccc83847d.address
  ci/chains/gaia/v5.0.5/ibc-0/keyring-test/user.info
  ci/chains/gaia/v5.0.5/ibc-0/keyring-test/user2.info
  ci/chains/gaia/v5.0.5/ibc-0/keyring-test/validator.info
  ci/chains/gaia/v5.0.5/ibc-0/user2_seed.json
  ci/chains/gaia/v5.0.5/ibc-0/user_seed.json
  ci/chains/gaia/v5.0.5/ibc-0/validator_seed.json
  ci/chains/gaia/v5.0.5/ibc-1/config/app.toml
  ci/chains/gaia/v5.0.5/ibc-1/config/client.toml
  ci/chains/gaia/v5.0.5/ibc-1/config/config.toml
  ci/chains/gaia/v5.0.5/ibc-1/config/genesis.json
  ci/chains/gaia/v5.0.5/ibc-1/config/gentx/gentx-1feb1ad566fa381f6e6b4afd639559e0505fd9d0.json
  ci/chains/gaia/v5.0.5/ibc-1/config/node_key.json
  ci/chains/gaia/v5.0.5/ibc-1/config/priv_validator_key.json
  ci/chains/gaia/v5.0.5/ibc-1/keyring-test/340bb9c429320d582a78e3c9997dedb9fe307082.address
  ci/chains/gaia/v5.0.5/ibc-1/keyring-test/408f79a6bfd105eb477b2433c8459a2aea93c34f.address
  ci/chains/gaia/v5.0.5/ibc-1/keyring-test/faebec57446ff6086960a12ad95a6d31787df226.address
  ci/chains/gaia/v5.0.5/ibc-1/keyring-test/user.info
  ci/chains/gaia/v5.0.5/ibc-1/keyring-test/user2.info
  ci/chains/gaia/v5.0.5/ibc-1/keyring-test/validator.info
  ci/chains/gaia/v5.0.5/ibc-1/user2_seed.json
  ci/chains/gaia/v5.0.5/ibc-1/user_seed.json
  ci/chains/gaia/v5.0.5/ibc-1/validator_seed.json
  ci/docker-compose.yml
  ci/gaia.Dockerfile
  ci/relayer.Dockerfile
  ci/run-gaiad.sh
  ci/simple_config.toml
Labels: CI/CD

#955 RESTful API
  .changelog/unreleased/features/843-rest-api.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  config.toml
  modules/src/ics24_host/error.rs
  relayer-cli/Cargo.toml
  relayer-cli/src/commands/start.rs
  relayer-rest/Cargo.toml
  relayer-rest/src/config.rs
  relayer-rest/src/handle.rs
  relayer-rest/src/lib.rs
  relayer-rest/src/server.rs
  relayer-rest/tests/mock.rs
  relayer/src/config.rs
  relayer/src/lib.rs
  relayer/src/rest.rs
  relayer/src/rest/error.rs
  relayer/src/rest/request.rs
  relayer/src/supervisor.rs
Labels: needs guide update

#1282 Derive `Debug`, `PartialEq` and `Eq` for module errors
  .changelog/unreleased/improvements/1281-derive-traits-module-errors.md
  modules/src/application/ics20_fungible_token_transfer/error.rs
  modules/src/ics02_client/error.rs
  modules/src/ics03_connection/error.rs
  modules/src/ics04_channel/error.rs
  modules/src/ics07_tendermint/error.rs
  modules/src/ics23_commitment/error.rs
  modules/src/ics23_commitment/merkle.rs
  modules/src/ics26_routing/error.rs
Labels: modules

#1274 Add ICS07 client upgrade to the MBT tests
  .changelog/unreleased/improvements/1311-mbt-test-client-upgrade.md
  modules/src/ics26_routing/handler.rs
  modules/tests/mbt.rs
  modules/tests/runner/mod.rs
  modules/tests/runner/step.rs
  modules/tests/support/model_based/IBC.cfg
  modules/tests/support/model_based/IBC.tla
  modules/tests/support/model_based/IBCDefinitions.tla
  modules/tests/support/model_based/IBCTests.cfg
  modules/tests/support/model_based/IBCTests.tla
  modules/tests/support/model_based/ICS02.tla
  modules/tests/support/model_based/ICS03.tla
Labels: testing
