Repository informalsystems/hermes, pull requests merged in 2021-07, with the labels that each got.

#1107 Implement basic "allow" filtering mechanism based on channel identifiers
  CHANGELOG.md
  config.toml
  relayer-cli/src/commands/query/packet.rs
  relayer/src/chain/cosmos.rs
  relayer/src/chain/mock.rs
  relayer/src/config.rs
  relayer/src/object.rs
  relayer/src/supervisor.rs
Labels: in progress

#1130 Implement query channel ends command
  CHANGELOG.md
  e2e/e2e/channel.py
  e2e/run.py
  relayer-cli/src/commands/query.rs
  relayer-cli/src/commands/query/channel_ends.rs
Labels: gravity, needs guide update

#1138 Adjust Hermes log messages
  relayer/src/foreign_client.rs
Labels: gravity

#1145 Add health checkup mechanism
  CHANGELOG.md
  Cargo.lock
  proto/src/lib.rs
  relayer/Cargo.toml
  relayer/src/chain/cosmos.rs
  relayer/src/chain/cosmos/compatibility.rs
  relayer/src/error.rs
Labels: gravity, needs guide update

#1144 Fix for schedule refreshing bug
  CHANGELOG.md
  relayer/src/link.rs
  relayer/src/worker/handle.rs
  relayer/src/worker/uni_chan_path.rs
Labels: gravity

#1146 Hermes retrying mechanism for packet clearing
  CHANGELOG.md
  ci/simple_config.toml
  config.toml
  relayer/src/chain/cosmos.rs
  relayer/src/channel.rs
  relayer/src/config.rs
  relayer/src/error.rs
  relayer/src/link.rs
  relayer/src/supervisor.rs
  relayer/src/worker.rs
  relayer/src/worker/map.rs
  relayer/src/worker/uni_chan_path.rs
Labels: gravity

#1123 Configuration reload
  CHANGELOG.md
  Cargo.lock
  modules/src/ics02_client/client_def.rs
  modules/src/ics02_client/msgs.rs
  modules/src/ics03_connection/connection.rs
  modules/src/ics03_connection/msgs.rs
  modules/src/ics04_channel/channel.rs
  modules/src/ics23_commitment/specs.rs
  modules/src/ics26_routing/handler.rs
  relayer-cli/Cargo.toml
  relayer-cli/src/application.rs
  relayer-cli/src/cli_utils.rs
  relayer-cli/src/commands/listen.rs
  relayer-cli/src/commands/query/packet.rs
  relayer-cli/src/commands/query/tx/events.rs
  relayer-cli/src/commands/start.rs
  relayer-cli/src/config.rs
  relayer/src/chain.rs
  relayer/src/chain/cosmos.rs
  relayer/src/chain/counterparty.rs
  relayer/src/chain/handle.rs
  relayer/src/chain/handle/prod.rs
  relayer/src/chain/mock.rs
  relayer/src/chain/runtime.rs
  relayer/src/channel.rs
  relayer/src/config.rs
  relayer/src/config/reload.rs
  relayer/src/connection.rs
  relayer/src/event/bus.rs
  relayer/src/event/monitor.rs
  relayer/src/foreign_client.rs
  relayer/src/object.rs
  relayer/src/registry.rs
  relayer/src/supervisor.rs
  relayer/src/supervisor/cmd.rs
  relayer/src/supervisor/dump_state.rs
  relayer/src/supervisor/error.rs
  relayer/src/supervisor/spawn.rs
  relayer/src/util.rs
  relayer/src/util/diff.rs
  relayer/src/worker.rs
  relayer/src/worker/channel.rs
  relayer/src/worker/client.rs
  relayer/src/worker/cmd.rs
  relayer/src/worker/connection.rs
  relayer/src/worker/handle.rs
  relayer/src/worker/map.rs
  relayer/src/worker/uni_chan_path.rs
Labels: gravity, needs guide update

#1142 Hermes "deny" channel filtering policy, and client state filter
  CHANGELOG.md
  config.toml
  modules/src/ics02_client/client_state.rs
  relayer/src/chain/mock.rs
  relayer/src/config.rs
  relayer/src/supervisor.rs
  relayer/src/supervisor/client_state_filter.rs
  relayer/src/supervisor/spawn.rs
Labels: gravity, needs guide update

#1134 Release Hermes v0.6.0
  CHANGELOG.md
  Cargo.lock
  config.toml
  guide/README.md
  guide/src/SUMMARY.md
  guide/src/commands/config.md
  guide/src/commands/global.md
  guide/src/commands/index.md
  guide/src/commands/queries/channel.md
  guide/src/config.md
  guide/src/features.md
  guide/src/help.md
  guide/src/index.md
  guide/src/installation.md
  guide/src/tutorials/local-chains/start.md
  modules/Cargo.toml
  proto/Cargo.toml
  relayer-cli/Cargo.toml
  relayer/Cargo.toml
  relayer/src/worker/uni_chan_path.rs
  telemetry/Cargo.toml
Labels: gravity

#1122 Clean-up unwraps in `query packet` CLI commands
  CHANGELOG.md
  relayer-cli/src/commands/query.rs
  relayer-cli/src/commands/query/packet.rs
  relayer-cli/src/commands/query/packet/ack.rs
  relayer-cli/src/commands/query/packet/acks.rs
  relayer-cli/src/commands/query/packet/commitment.rs
  relayer-cli/src/commands/query/packet/commitments.rs
  relayer-cli/src/commands/query/packet/unreceived_acks.rs
  relayer-cli/src/commands/query/packet/unreceived_packets.rs
  relayer/src/chain/counterparty.rs
  relayer/src/link.rs
  relayer/src/supervisor/error.rs
Labels: gravity

#1077 Add bulk upgrade CLI
  CHANGELOG.md
  docs/architecture/adr-006-hermes-v0.2-usecases.md
  relayer-cli/src/commands/tx.rs
  relayer-cli/src/commands/tx/client.rs
  relayer-cli/src/commands/upgrade.rs
  relayer/src/foreign_client.rs
Labels: needs guide update

#1205 Recover from missed RPC events after WebSocket subscription is closed by Tendermint
  CHANGELOG.md
  Cargo.lock
  e2e/run.py
  relayer-cli/src/commands/listen.rs
  relayer/src/event/monitor.rs
  relayer/src/link/relay_path.rs
  relayer/src/supervisor.rs
  relayer/src/util/stream.rs
  relayer/src/worker/channel.rs
  relayer/src/worker/client.rs
  relayer/src/worker/cmd.rs
  relayer/src/worker/connection.rs
  relayer/src/worker/handle.rs
  relayer/src/worker/map.rs
  relayer/src/worker/packet.rs
Labels: gravity

#1164 Use `#![no_std]` for ibc-proto crate
  Cargo.lock
  Cargo.toml
  no-std-check/.gitignore
  no-std-check/Cargo.lock
  no-std-check/Cargo.toml
  no-std-check/README.md
  no-std-check/src/lib.rs
  proto/Cargo.toml
  proto/src/lib.rs
Labels: no-std
