Repository informalsystems/hermes, pull requests merged in 2021-06, with the labels that each got.

#995 Include chain-id in hermes query clients output
  CHANGELOG.md
  relayer-cli/src/commands/query.rs
  relayer-cli/src/commands/query/clients.rs
  relayer/src/chain/cosmos.rs
Labels: needs guide update

#985 Add telemetry and Prometheus endpoint
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  config.toml
  modules/src/events.rs
  relayer-cli/Cargo.toml
  relayer-cli/src/commands/start.rs
  relayer/Cargo.toml
  relayer/src/chain/handle.rs
  relayer/src/config.rs
  relayer/src/lib.rs
  relayer/src/link.rs
  relayer/src/supervisor.rs
  relayer/src/telemetry.rs
  relayer/src/worker.rs
  relayer/src/worker/channel.rs
  relayer/src/worker/client.rs
  relayer/src/worker/map.rs
  relayer/src/worker/uni_chan_path.rs
  telemetry/Cargo.toml
  telemetry/src/lib.rs
  telemetry/src/server.rs
  telemetry/src/state.rs
Labels: needs guide update

#1033 Add `host` parameter to `telemetry` config
  config.toml
  relayer-cli/src/commands/start.rs
  relayer/src/config.rs
  telemetry/src/lib.rs
  telemetry/src/server.rs
Labels: needs guide update, telemetry

#1091 Change hermes to use broadcast_tx_sync for transaction submission
  CHANGELOG.md
  Cargo.lock
  ci/simple_config.toml
  config.toml
  e2e/e2e/cmd.py
  e2e/e2e/packet.py
  modules/src/query.rs
  relayer-cli/src/commands/query.rs
  relayer-cli/src/commands/query/packet.rs
  relayer-cli/src/commands/query/tx.rs
  relayer-cli/src/commands/query/tx/events.rs
  relayer-cli/src/commands/start.rs
  relayer-cli/tests/fixtures/two_chains.toml
  relayer/Cargo.toml
  relayer/src/chain/cosmos.rs
  relayer/src/chain/counterparty.rs
  relayer/src/chain/mock.rs
  relayer/src/config.rs
  relayer/src/error.rs
  relayer/src/foreign_client.rs
  relayer/src/link.rs
  relayer/src/transfer.rs
  relayer/tests/config/fixtures/relayer_conf_example.toml
  scripts/gm/bin/lib-gm
Labels: needs guide update

#1019 Connection worker
  CHANGELOG.md
  ci/chains/gaia/v4.2.0/ibc-0/config/gentx/gentx-45c0b2dd4b449f23fa5d112b162fb05f9f4a4812.json
  ci/chains/gaia/v4.2.0/ibc-0/key_seed.json
  ci/chains/gaia/v4.2.0/ibc-0/keyring-test/4a35e9f33e0b0b8ffb7accc43521443bee1d2ae4.address
  ci/chains/gaia/v4.2.0/ibc-0/keyring-test/e3e3d299bc23f66cf82b577e27750065b1c358d2.address
  ci/chains/gaia/v4.2.0/ibc-1/config/gentx/gentx-0a4306ad6829fcbb9a36c06aed7f957648a28e3a.json
  ci/chains/gaia/v4.2.0/ibc-1/key_seed.json
  ci/chains/gaia/v4.2.0/ibc-1/keyring-test/4028568a292af8ad167db01faf2514c97862ede6.address
  ci/chains/gaia/v4.2.0/ibc-1/keyring-test/eca2936a58b8ab7c073373e00e853ef842119d7e.address
  ci/simple_config.toml
  e2e/e2e/connection.py
  e2e/run.py
  modules/src/events.rs
  modules/src/ics03_connection/connection.rs
  modules/src/ics03_connection/events.rs
  relayer-cli/src/commands/query/connections.rs
  relayer-cli/src/commands/tx/connection.rs
  relayer/src/chain.rs
  relayer/src/chain/cosmos.rs
  relayer/src/chain/counterparty.rs
  relayer/src/chain/handle.rs
  relayer/src/chain/handle/prod.rs
  relayer/src/chain/mock.rs
  relayer/src/chain/runtime.rs
  relayer/src/channel.rs
  relayer/src/connection.rs
  relayer/src/object.rs
  relayer/src/supervisor.rs
  relayer/src/worker.rs
  relayer/src/worker/connection.rs
  relayer/src/worker/map.rs
  scripts/setup-chains
  telemetry/src/state.rs
Labels: needs guide update

#1098 Release Hermes v0.5.0
  CHANGELOG.md
  Cargo.lock
  guide/README.md
  guide/src/SUMMARY.md
  guide/src/commands/global.md
  guide/src/commands/keys/index.md
  guide/src/commands/listen/index.md
  guide/src/commands/misbehaviour/index.md
  guide/src/commands/path-setup/channels.md
  guide/src/commands/path-setup/clients.md
  guide/src/commands/path-setup/connections.md
  guide/src/commands/queries/channel.md
  guide/src/commands/queries/client.md
  guide/src/commands/queries/connection.md
  guide/src/commands/queries/index.md
  guide/src/commands/queries/packet.md
  guide/src/commands/queries/tx.md
  guide/src/commands/raw/channel-close.md
  guide/src/commands/raw/channel-open.md
  guide/src/commands/raw/client.md
  guide/src/commands/raw/connection.md
  guide/src/commands/raw/packet.md
  guide/src/commands/relaying/channel.md
  guide/src/commands/relaying/handshakes.md
  guide/src/commands/upgrade/test.md
  guide/src/config.md
  guide/src/features.md
  guide/src/features/matrix.md
  guide/src/help.md
  guide/src/index.md
  guide/src/installation.md
  guide/src/pre_requisites.md
  guide/src/tutorials/local-chains/gaia.md
  guide/src/tutorials/local-chains/identifiers.md
  guide/src/tutorials/local-chains/raw/client.md
  guide/src/tutorials/local-chains/relay-paths/multiple-paths.md
  guide/src/tutorials/local-chains/start.md
  modules/Cargo.toml
  proto/Cargo.toml
  relayer-cli/Cargo.toml
  relayer/Cargo.toml
  relayer/src/chain/cosmos.rs
  relayer/src/chain/mock.rs
  relayer/src/config.rs
  relayer/src/link.rs
  telemetry/Cargo.toml
Labels: in progress

#1128 Syntactic validation of configuration file
  CHANGELOG.md
  relayer-cli/src/application.rs
  relayer-cli/src/commands.rs
  relayer-cli/src/commands/config/validate.rs
  relayer-cli/src/commands/start.rs
  relayer-cli/src/components.rs
  relayer-cli/src/config.rs
  relayer/src/config.rs
Labels: needs guide update

#1136 Add inline documentation to example config.toml
  CHANGELOG.md
  config.toml
  guide/src/config.md
Labels: needs guide update
