Repository informalsystems/hermes, pull requests merged in 2022-08, with the labels that each got.

#2412 Object safe Protobuf
  Cargo.lock
  modules/src/applications/transfer/error.rs
  modules/src/applications/transfer/msgs/transfer.rs
  modules/src/clients/ics07_tendermint/client_def.rs
  modules/src/clients/ics07_tendermint/client_state.rs
  modules/src/clients/ics07_tendermint/consensus_state.rs
  modules/src/clients/ics07_tendermint/header.rs
  modules/src/clients/ics07_tendermint/misbehaviour.rs
  modules/src/core/ics02_client/client_consensus.rs
  modules/src/core/ics02_client/client_state.rs
  modules/src/core/ics02_client/error.rs
  modules/src/core/ics02_client/header.rs
  modules/src/core/ics02_client/height.rs
  modules/src/core/ics02_client/misbehaviour.rs
  modules/src/core/ics02_client/msgs/create_client.rs
  modules/src/core/ics02_client/msgs/misbehavior.rs
  modules/src/core/ics02_client/msgs/update_client.rs
  modules/src/core/ics02_client/msgs/upgrade_client.rs
  modules/src/core/ics02_client/trust_threshold.rs
  modules/src/core/ics03_connection/connection.rs
  modules/src/core/ics03_connection/msgs/conn_open_ack.rs
  modules/src/core/ics03_connection/msgs/conn_open_confirm.rs
  modules/src/core/ics03_connection/msgs/conn_open_init.rs
  modules/src/core/ics03_connection/msgs/conn_open_try.rs
  modules/src/core/ics03_connection/version.rs
  modules/src/core/ics04_channel/channel.rs
  modules/src/core/ics04_channel/error.rs
  modules/src/core/ics04_channel/msgs/acknowledgement.rs
  modules/src/core/ics04_channel/msgs/chan_close_confirm.rs
  modules/src/core/ics04_channel/msgs/chan_close_init.rs
  modules/src/core/ics04_channel/msgs/chan_open_ack.rs
  modules/src/core/ics04_channel/msgs/chan_open_confirm.rs
  modules/src/core/ics04_channel/msgs/chan_open_init.rs
  modules/src/core/ics04_channel/msgs/chan_open_try.rs
  modules/src/core/ics04_channel/msgs/recv_packet.rs
  modules/src/core/ics04_channel/msgs/timeout.rs
  modules/src/core/ics04_channel/msgs/timeout_on_close.rs
  modules/src/core/ics26_routing/error.rs
  modules/src/core/ics26_routing/msgs.rs
  modules/src/mock/client_state.rs
  modules/src/mock/header.rs
  modules/src/mock/misbehaviour.rs
  proto/Cargo.toml
  proto/src/lib.rs
  proto/src/protobuf/erased.rs
  proto/src/protobuf/error.rs
  proto/src/protobuf/mod.rs
  relayer/src/chain/cosmos.rs
  relayer/src/error.rs
Labels: adr011-impl

#2480 relayer: Fix one-past-the-limit flaw in message batching
  .changelog/unreleased/bug-fixes/ibc-relayer/2477-prevent-oversized-tx-batch.md
  relayer/src/chain/cosmos/batch.rs
  relayer/src/config/types.rs
  relayer/src/error.rs
Labels: relayer

#2527 Remove `AnyMisbehaviour` from modules
  modules/src/core/ics02_client/header.rs
  modules/src/core/ics02_client/misbehaviour.rs
  modules/src/core/ics02_client/msgs.rs
  modules/src/core/ics02_client/msgs/misbehaviour.rs
  relayer/src/foreign_client.rs
  relayer/src/light_client.rs
  relayer/src/misbehaviour.rs
Labels: adr011-impl

#2572 Remove ChannelReaderLightClient
  modules/src/clients/ics07_tendermint/client_state.rs
  modules/src/core/ics02_client/client_state.rs
  modules/src/core/ics04_channel/context.rs
  modules/src/core/ics04_channel/handler/acknowledgement.rs
  modules/src/core/ics04_channel/handler/chan_close_confirm.rs
  modules/src/core/ics04_channel/handler/chan_close_init.rs
  modules/src/core/ics04_channel/handler/chan_open_ack.rs
  modules/src/core/ics04_channel/handler/chan_open_confirm.rs
  modules/src/core/ics04_channel/handler/chan_open_init.rs
  modules/src/core/ics04_channel/handler/chan_open_try.rs
  modules/src/core/ics04_channel/handler/recv_packet.rs
  modules/src/core/ics04_channel/handler/timeout.rs
  modules/src/core/ics04_channel/handler/timeout_on_close.rs
  modules/src/core/ics04_channel/handler/verify.rs
  modules/src/core/ics04_channel/handler/write_acknowledgement.rs
  modules/src/core/ics26_routing/context.rs
  modules/src/mock/client_state.rs
  relayer/src/client_state.rs
Labels: adr011-impl

#2570 Merge `Clientdef` into `Clientstate`
  modules/src/clients/ics07_tendermint/client_def.rs
  modules/src/clients/ics07_tendermint/client_state.rs
  modules/src/clients/ics07_tendermint/mod.rs
  modules/src/core/ics02_client/client_def.rs
  modules/src/core/ics02_client/client_state.rs
  modules/src/core/ics02_client/handler/create_client.rs
  modules/src/core/ics02_client/handler/update_client.rs
  modules/src/core/ics02_client/handler/upgrade_client.rs
  modules/src/core/ics02_client/mod.rs
  modules/src/core/ics02_client/msgs.rs
  modules/src/core/ics02_client/msgs/create_client.rs
  modules/src/core/ics02_client/msgs/upgrade_client.rs
  modules/src/core/ics03_connection/handler/verify.rs
  modules/src/core/ics04_channel/context.rs
  modules/src/core/ics04_channel/handler/acknowledgement.rs
  modules/src/core/ics04_channel/handler/chan_close_confirm.rs
  modules/src/core/ics04_channel/handler/chan_close_init.rs
  modules/src/core/ics04_channel/handler/chan_open_ack.rs
  modules/src/core/ics04_channel/handler/chan_open_confirm.rs
  modules/src/core/ics04_channel/handler/chan_open_init.rs
  modules/src/core/ics04_channel/handler/chan_open_try.rs
  modules/src/core/ics04_channel/handler/recv_packet.rs
  modules/src/core/ics04_channel/handler/timeout.rs
  modules/src/core/ics04_channel/handler/timeout_on_close.rs
  modules/src/core/ics04_channel/handler/verify.rs
  modules/src/core/ics04_channel/handler/write_acknowledgement.rs
  modules/src/core/ics26_routing/context.rs
  modules/src/core/ics26_routing/handler.rs
  modules/src/core/ics26_routing/msgs.rs
  modules/src/mock/client_def.rs
  modules/src/mock/client_state.rs
  modules/src/mock/mod.rs
  modules/tests/runner/mod.rs
  relayer-cli/src/commands/query/channel_ends.rs
  relayer/src/chain/cosmos.rs
  relayer/src/chain/counterparty.rs
  relayer/src/chain/mock.rs
  relayer/src/client_state.rs
  relayer/src/foreign_client.rs
  tools/integration-test/src/tests/client_settings.rs
Labels: adr011-impl

#2533 Introduce crate `ibc-chain-registry` and `hermes config auto` to automatically generate a config file
  .changelog/config.toml
  .changelog/unreleased/features/chain-registry/2187-auto-config.md
  .changelog/unreleased/features/ibc-relayer-cli/2187-auto-config.md
  .changelog/unreleased/features/ibc-relayer/2187-auto-config.md
  Cargo.lock
  Cargo.toml
  README.md
  docs/architecture/adr-010-unified-cli-arguments-hermes.md
  guide/src/commands/config.md
  guide/src/features/matrix.md
  ibc-chain-registry/Cargo.toml
  ibc-chain-registry/src/asset_list.rs
  ibc-chain-registry/src/chain.rs
  ibc-chain-registry/src/constants.rs
  ibc-chain-registry/src/error.rs
  ibc-chain-registry/src/fetchable.rs
  ibc-chain-registry/src/formatter.rs
  ibc-chain-registry/src/lib.rs
  ibc-chain-registry/src/paths.rs
  ibc-chain-registry/src/querier.rs
  relayer-cli/Cargo.toml
  relayer-cli/example
  relayer-cli/src/chain_registry.rs
  relayer-cli/src/commands/config.rs
  relayer-cli/src/commands/config/auto.rs
  relayer-cli/src/lib.rs
  relayer/src/chain/cosmos.rs
  relayer/src/config.rs
  relayer/src/config/filter.rs
  relayer/src/config/proof_specs.rs
Labels: enhancement, configuration
