Repository informalsystems/hermes, pull requests merged in 2023-01, with the labels that each got.

#2994 Add description to contributing & issue templates for applying labels
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: A: admin

#3007 Add some documentation for a test that uses the `BinaryChannelTest` trait
  tools/integration-test/src/tests/ordered_channel.rs
  tools/test-framework/src/docs/walkthroughs/memo.rs
  tools/test-framework/src/docs/walkthroughs/mod.rs
  tools/test-framework/src/docs/walkthroughs/ordered_channel.rs
  tools/test-framework/src/docs/walkthroughs/simple.rs
Labels: I: documentation, I: CI/CD

#3018 Run `multi-chains` workflow on all PRs marked with the `CI: multi-chains` label
  .github/workflows/integration.yaml
  .github/workflows/multi-chains.yaml
Labels: I: CLI

#3019 Update cosmos.nix to latest version
  .github/workflows/integration.yaml
  flake.lock
Labels: I: dependencies, I: CI/CD, CI: multi-chains

#3032 Fix packet forwarding tests
  .changelog/unreleased/bug-fixes/ibc-integration-test/3025-fix-packet-forwarding-tests.md
  .github/workflows/integration.yaml
  tools/integration-test/src/tests/forward/forward_hop_transfer.rs
  tools/integration-test/src/tests/forward/forward_transfer.rs
  tools/integration-test/src/tests/forward/memo.rs
  tools/integration-test/src/tests/forward/mod.rs
  tools/test-framework/src/chain/cli/transfer.rs
Labels: O: testability

#3051 Refactor message batch worker implementation to make use of auto-trait-style context-generic programming
  crates/relayer-cosmos/src/contexts/full/relay.rs
  crates/relayer-cosmos/src/full/impls/relay.rs
  crates/relayer-framework/src/base/core/traits/error.rs
  crates/relayer-framework/src/full/batch/impls/mod.rs
  crates/relayer-framework/src/full/batch/impls/spawn.rs
  crates/relayer-framework/src/full/batch/traits/mod.rs
  crates/relayer-framework/src/full/batch/traits/spawn.rs
  crates/relayer-framework/src/full/batch/worker.rs
  crates/relayer-framework/src/full/one_for_all/impls/relay/error.rs
  crates/relayer-framework/src/full/one_for_all/traits/relay.rs
Labels: O: relayer-next
